#docker-compose
version: '3.8'
services:
  calculator-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: ["npx", "serve", "-s", "."]