version: '3.8'
services:
  calculator-app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: ["npx", "serve", "-l", "4000", "-s", "."]
